import {
  BadgeCheck,
  BatteryCharging,
  BriefcaseBusiness,
  GraduationCap,
  Headphones,
  Luggage,
  Music,
  ShieldCheck,
  SlidersHorizontal,
  Trophy,
  User,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { Category, Product, RetailerOffer, ScoreRow } from "@/types/compare";

export const compareCategories: Category[] = [
  { id: "all-deals", label: "All Deals" },
  { id: "electronics", label: "Electronics" },
  { id: "home", label: "Home" },
  { id: "beauty", label: "Beauty" },
  { id: "fashion", label: "Fashion" },
  { id: "kitchen", label: "Kitchen" },
  { id: "gaming", label: "Gaming" },
  { id: "sports", label: "Sports" },
  { id: "automotive", label: "Automotive" },
  { id: "office", label: "Office" },
];

export const extraCompareCategories: Category[] = [
  { id: "books", label: "Books" },
  { id: "toys", label: "Toys" },
  { id: "outdoors", label: "Outdoors" },
  { id: "health", label: "Health" },
  { id: "pet-supplies", label: "Pet Supplies" },
];

export const userFitRows: Array<{ id: string; label: string; icon: LucideIcon }> = [
  { id: "travelers", label: "Frequent Travelers", icon: Luggage },
  { id: "office", label: "Office / Calls", icon: BriefcaseBusiness },
  { id: "music", label: "Music Lovers", icon: Music },
  { id: "students", label: "Students", icon: GraduationCap },
  { id: "workout", label: "Workout / On-the-go", icon: Zap },
];

export const mockProducts: Product[] = [
  {
    id: "sony-wh-1000xm5",
    slug: "sony-wh-1000xm5",
    name: "Sony WH-1000XM5",
    subtitle: "Wireless Noise Cancelling Headphones",
    rating: 4.6,
    reviews: 12842,
    reviewTrust: "High review trust",
    tags: ["Noise Cancelling", "30H Battery", "Comfort Fit", "Bluetooth 5.2"],
    currentPrice: 299.99,
    listPrice: 389.99,
    discountPercent: 23,
    verdict: "WAIT",
    scores: {
      aiBuy: 76,
      price: 62,
      reviewTrust: "High",
      performance: 85,
      comfort: 68,
      battery: 80,
      features: 70,
    },
    bestFor: "ANC",
    imageSrc: "/compare/sony-wh-1000xm5-black.png",
    imageAlt: "Sony WH-1000XM5 black headphones",
    pros: ["Excellent noise cancellation", "Great battery life (30 hours)", "Lightweight and comfortable", "Multipoint connection"],
    cons: ["Call quality could be better", "Foldable design is bulky", "Touch controls can be finicky"],
    userFit: {
      travelers: "Best ANC performance",
      office: "Good",
      music: "More detailed sound",
      students: "Better battery life",
      workout: "Lightweight",
    },
  },
  {
    id: "bose-quietcomfort-ultra",
    slug: "bose-quietcomfort-ultra",
    name: "Bose QuietComfort Ultra",
    subtitle: "Wireless Noise Cancelling Headphones",
    rating: 4.7,
    reviews: 8215,
    reviewTrust: "High review trust",
    tags: ["Noise Cancelling", "24H Battery", "Premium Comfort", "Bluetooth 5.3"],
    currentPrice: 279,
    listPrice: 319,
    discountPercent: 12,
    verdict: "BUY",
    scores: {
      aiBuy: 84,
      price: 78,
      reviewTrust: "High",
      performance: 87,
      comfort: 90,
      battery: 72,
      features: 75,
    },
    bestFor: "Comfort",
    imageSrc: "/compare/bose-qc-ultra-black.png",
    imageAlt: "Bose QuietComfort Ultra black headphones",
    pros: ["Superior comfort for long use", "Better call quality", "More natural sound profile", "Premium build quality"],
    cons: ["Slightly shorter battery life", "No LDAC codec support", "Less app customization"],
    userFit: {
      travelers: "More comfortable for long flights",
      office: "Better call quality",
      music: "Well-balanced sound",
      students: "Better comfort for study",
      workout: "Secure and comfortable fit",
    },
  },
  {
    id: "sennheiser-momentum-4",
    slug: "sennheiser-momentum-4",
    name: "Sennheiser Momentum 4",
    subtitle: "Wireless Adaptive Noise Cancelling Headphones",
    rating: 4.5,
    reviews: 6930,
    reviewTrust: "High review trust",
    tags: ["Adaptive ANC", "60H Battery", "Hi-Fi Sound", "Bluetooth 5.2"],
    currentPrice: 249.95,
    listPrice: 379.95,
    discountPercent: 34,
    verdict: "BUY",
    scores: {
      aiBuy: 82,
      price: 86,
      reviewTrust: "High",
      performance: 84,
      comfort: 76,
      battery: 96,
      features: 74,
    },
    bestFor: "Battery",
    imageAlt: "Sennheiser Momentum 4 headphones placeholder",
    pros: ["Outstanding battery life", "Detailed sound profile", "Strong sale pricing", "Comfortable fit"],
    cons: ["ANC trails Sony and Bose", "Controls need setup", "Case is larger"],
    userFit: {
      travelers: "Longest battery life",
      office: "Clear enough for calls",
      music: "Detailed sound",
      students: "Best battery for study",
      workout: "Less compact",
    },
  },
  {
    id: "apple-airpods-max",
    slug: "apple-airpods-max",
    name: "Apple AirPods Max",
    subtitle: "Over-Ear Wireless Headphones",
    rating: 4.4,
    reviews: 17720,
    reviewTrust: "High review trust",
    tags: ["Spatial Audio", "20H Battery", "Apple H1", "Premium Build"],
    currentPrice: 449,
    listPrice: 549,
    discountPercent: 18,
    verdict: "WAIT",
    scores: {
      aiBuy: 70,
      price: 54,
      reviewTrust: "High",
      performance: 86,
      comfort: 72,
      battery: 62,
      features: 82,
    },
    bestFor: "Apple",
    imageAlt: "Apple AirPods Max placeholder",
    pros: ["Excellent Apple integration", "Premium build quality", "Strong transparency mode", "Spatial audio support"],
    cons: ["Expensive", "Heavy for long sessions", "Case protection is limited"],
    userFit: {
      travelers: "Great ANC but heavy",
      office: "Excellent Apple calls",
      music: "Spatial audio strength",
      students: "High price",
      workout: "Too heavy",
    },
  },
  {
    id: "beats-studio-pro",
    slug: "beats-studio-pro",
    name: "Beats Studio Pro",
    subtitle: "Wireless Noise Cancelling Headphones",
    rating: 4.3,
    reviews: 5120,
    reviewTrust: "Medium review trust",
    tags: ["ANC", "40H Battery", "USB-C Audio", "Fast Fuel"],
    currentPrice: 199.99,
    listPrice: 349.99,
    discountPercent: 43,
    verdict: "BUY",
    scores: {
      aiBuy: 78,
      price: 90,
      reviewTrust: "Medium",
      performance: 74,
      comfort: 70,
      battery: 86,
      features: 76,
    },
    bestFor: "Value",
    imageAlt: "Beats Studio Pro placeholder",
    pros: ["Aggressive discount", "Good battery life", "Works across iOS and Android", "Compact profile"],
    cons: ["ANC is not class-leading", "Clamp can feel tight", "Mixed review sentiment"],
    userFit: {
      travelers: "Good value ANC",
      office: "Usable call quality",
      music: "Punchy sound",
      students: "Best budget pick",
      workout: "Secure fit",
    },
  },
];

export const scoreRows: ScoreRow[] = [
  { id: "aiBuy", label: "AI Buy Score", icon: BadgeCheck, type: "score" },
  { id: "price", label: "Price Score", icon: SlidersHorizontal, type: "score" },
  { id: "reviewTrust", label: "Review Trust", icon: ShieldCheck, type: "trust" },
  { id: "performance", label: "Performance (ANC)", icon: Headphones, type: "score" },
  { id: "comfort", label: "Comfort", icon: User, type: "score" },
  { id: "battery", label: "Battery Life", icon: BatteryCharging, type: "score" },
  { id: "features", label: "Features", icon: BriefcaseBusiness, type: "score" },
  { id: "bestFor", label: "Best For", icon: Trophy, type: "text" },
  { id: "verdict", label: "Verdict", icon: Trophy, type: "verdict" },
];

export const aiRecommendation = {
  title: "Bose QuietComfort Ultra is the better choice for most users.",
  body: "It scores higher in overall value, comfort, and review sentiment while having a similar price.",
  confidence: 82,
  confidenceLabel: "High",
  sourceCount: "45,000+",
};

export const retailerOffers: RetailerOffer[] = [
  {
    id: "amazon",
    retailer: "Amazon",
    logoSrc: "/home/logos/amazon.svg",
    offers: {
      "sony-wh-1000xm5": { price: 299.99, discountPercent: 23 },
      "bose-quietcomfort-ultra": { price: 279, discountPercent: 12 },
    },
  },
  {
    id: "best-buy",
    retailer: "Best Buy",
    logoSrc: "/home/logos/bestbuy.svg",
    offers: {
      "sony-wh-1000xm5": { price: 329.99 },
      "bose-quietcomfort-ultra": { price: 279.99 },
    },
  },
  {
    id: "walmart",
    retailer: "Walmart",
    logoSrc: "/home/logos/walmart.svg",
    offers: {
      "sony-wh-1000xm5": { price: 319 },
      "bose-quietcomfort-ultra": { price: 279 },
    },
  },
  {
    id: "target",
    retailer: "Target",
    logoSrc: "/home/logos/target.svg",
    offers: {
      "sony-wh-1000xm5": { price: 329.99 },
      "bose-quietcomfort-ultra": { price: 279.99 },
    },
  },
  {
    id: "costco",
    retailer: "Costco",
    offers: {
      "sony-wh-1000xm5": { price: 307.99 },
      "bose-quietcomfort-ultra": { price: 284 },
    },
  },
  {
    id: "bh-photo",
    retailer: "B&H",
    offers: {
      "sony-wh-1000xm5": { price: 298, discountPercent: 24 },
      "bose-quietcomfort-ultra": { price: 289, discountPercent: 9 },
    },
  },
  {
    id: "newegg",
    retailer: "Newegg",
    offers: {
      "sony-wh-1000xm5": { price: 309 },
      "bose-quietcomfort-ultra": { price: 281.99 },
    },
  },
  {
    id: "sams-club",
    retailer: "Sam's Club",
    offers: {
      "sony-wh-1000xm5": { price: 315 },
      "bose-quietcomfort-ultra": { price: 286 },
    },
  },
  {
    id: "ebay",
    retailer: "eBay",
    offers: {
      "sony-wh-1000xm5": { price: 289.99 },
      "bose-quietcomfort-ultra": { price: 268 },
    },
  },
  {
    id: "adorama",
    retailer: "Adorama",
    offers: {
      "sony-wh-1000xm5": { price: 299 },
      "bose-quietcomfort-ultra": { price: 279.95 },
    },
  },
  {
    id: "crutchfield",
    retailer: "Crutchfield",
    offers: {
      "sony-wh-1000xm5": { price: 329.99 },
      "bose-quietcomfort-ultra": { price: 299 },
    },
  },
  {
    id: "dell",
    retailer: "Dell",
    offers: {
      "sony-wh-1000xm5": { price: 319.99 },
      "bose-quietcomfort-ultra": { price: 279, discountPercent: 12 },
    },
  },
];
